language: java

jdk:
  - oraclejdk8

after_success:
  - gradle jacocoTestReport coveralls javadoc
  - .travis/push-javadoc-to-gh-pages.sh
  
env:
  global:
    - secure: "H+X0sl3Jc7B/nC/ommaWpWbcWdffJclA/32Mphbv6O1TFw8mBJdWiiUkzl8p0HO78MsGboiMP1xlhmyvli7mYTb59iRLHTdkcfQ4Po+SNBrDroQE3o9tL+PAY4PFHAV1sPq53NccMi81rliQG2rVye1ktjCYPQW6cP+OY6Nwo/c="

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
